version: "3.8"

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    image: anpr/tomcat  
    container_name: anpr-tomcat
    ports:
      - "80:8080"
    volumes:
      - /opt/anpr/resources:/opt/anpr/resources
    restart: always
networks:
  default:
    name: anpr_net
    external: true
